#!/bin/zsh

swift package \
    --allow-writing-to-directory ./docs \
    generate-documentation --target FireKit \
    --disable-indexing \
    --transform-for-static-hosting \
    --hosting-base-path FireKit \
    --output-path ./docs
